### ISSUE TITLE
[CR010] Drink recommendations

### ISSUE THREAD

**Issue by olliwho** [sw21-tug/Team_03#10]
As a logged in user
I want to get recommended drinks based on best rated drinks
So that i do not have to search so long

Acceptance Criteria:

- [ ] The is a section on the home page labeled "Recommended drinks"
- [ ] In this list there are high rated drinks shown

**Comment by olliwho** [comment]
Time Estimate: 3

List of all drinks already exists, just have to sort them by rating, based on issue #7

**Comment by xsoliah** [comment]
Recommendet sind zufällige 5, Trending sind top 15 nach rating sortiert, search bar und icon kommen weg, mit see all kommt man auf eine neue Seite
